# Generated by Django 2.2.7 on 2019-11-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('photo_url', models.CharField(default='N/A', max_length=255)),
                ('email', models.CharField(default='N/A', max_length=100)),
                ('about_me', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('description', models.CharField(default='N/A', max_length=100)),
                ('image', models.CharField(default='N/A', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='canvas_art_app.Category')),
            ],
        ),
    ]
